// <auto-generated />
namespace MVCAssignment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _init1328 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_init1328));
        
        string IMigrationMetadata.Id
        {
            get { return "202212121011311__init1328"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
